### PR TITLE
open ipython from inside cloned repo

### PR DESCRIPTION
**Pull request by anaderi**

### CODE REVIEW

**Comment by betatim** [comment]
Three thoughts (repeated from gitter):

* should we just clone directly to `$HOME`?
* should we add a `Welcome.ipynb` to explain a bit what just happened?
* should we switch the order of notebook starting and cloning? This would mean you could 'debug' the case where the clone fails or takes a long time

**Comment by betatim** [comment]
Regarding the third point, we could do `git clone $JPY_GITHUBURL $NOTEBOOK_DIR > $HOME/git.log 2>&1 &` to get the notebook up as soon as possible and capture the git output for debugging

**Comment by anaderi** [comment]
added

**Comment by betatim** [comment]
LGTM

**Pull request merged**
